package acme.server.entity;

// Generated 30/11/2011 12:52:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Classification generated by hbm2java
 */
public class Classification implements java.io.Serializable {

	private Long idClassification;
	private String name;
	private Set<Material> materials = new HashSet<Material>(0);

	public Classification() {
	}

	public Classification(String name, Set<Material> materials) {
		this.name = name;
		this.materials = materials;
	}

	public Long getIdClassification() {
		return this.idClassification;
	}

	public void setIdClassification(Long idClassification) {
		this.idClassification = idClassification;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

}
