package acme.server.entity;

// Generated 30/11/2011 12:52:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Collection generated by hbm2java
 */
public class Collection implements java.io.Serializable {

	private long idCollection;
	private TicketPrice ticketPrice;
	private String name;
	private String letters;
	private Boolean reserve;
	private Set<Material> materials = new HashSet<Material>(0);

	public Collection() {
	}

	public Collection(long idCollection) {
		this.idCollection = idCollection;
	}

	public Collection(long idCollection, TicketPrice ticketPrice, String name,
			String letters, Boolean reserve, Set<Material> materials) {
		this.idCollection = idCollection;
		this.ticketPrice = ticketPrice;
		this.name = name;
		this.letters = letters;
		this.reserve = reserve;
		this.materials = materials;
	}

	public long getIdCollection() {
		return this.idCollection;
	}

	public void setIdCollection(long idCollection) {
		this.idCollection = idCollection;
	}

	public TicketPrice getTicketPrice() {
		return this.ticketPrice;
	}

	public void setTicketPrice(TicketPrice ticketPrice) {
		this.ticketPrice = ticketPrice;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLetters() {
		return this.letters;
	}

	public void setLetters(String letters) {
		this.letters = letters;
	}

	public Boolean getReserve() {
		return this.reserve;
	}

	public void setReserve(Boolean reserve) {
		this.reserve = reserve;
	}

	public Set<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

}
