package acme.server.entity;

// Generated 30/11/2011 12:52:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * ContactCustomer generated by hbm2java
 */
public class ContactCustomer implements java.io.Serializable {

	private long idCustomer;
	private Customer customer;
	private String firstName;
	private String lastName;
	private String phone;
	private Boolean validated;

	public ContactCustomer() {
	}

	public ContactCustomer(Customer customer) {
		this.customer = customer;
	}

	public ContactCustomer(Customer customer, String firstName,
			String lastName, String phone, Boolean validated) {
		this.customer = customer;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phone = phone;
		this.validated = validated;
	}

	public long getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(long idCustomer) {
		this.idCustomer = idCustomer;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Boolean getValidated() {
		return this.validated;
	}

	public void setValidated(Boolean validated) {
		this.validated = validated;
	}

}
