package acme.server.entity;

// Generated 30/11/2011 12:52:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idCustomer;
	private String firstName;
	private String lastName;
	private Long dni;
	private String address;
	private String phone;
	private Date birthday;
	private Date registerDate;
	private ContactCustomer contactCustomer;
	private Set<Loan> loans = new HashSet<Loan>(0);
	private String mail;

	public Customer() {
	}

	public Customer(String firstName, String lastName, Long dni,
			String address, String phone, Date birthday, Date registerDate,
			ContactCustomer contactCustomer, Set<Loan> loans, String mail) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.dni = dni;
		this.address = address;
		this.phone = phone;
		this.birthday = birthday;
		this.registerDate = registerDate;
		this.contactCustomer = contactCustomer;
		this.loans = loans;
		this.setMail(mail);
	}

	public Long getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(Long idCustomer) {
		this.idCustomer = idCustomer;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Long getDni() {
		return this.dni;
	}

	public void setDni(Long dni) {
		this.dni = dni;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public ContactCustomer getContactCustomer() {
		return this.contactCustomer;
	}

	public void setContactCustomer(ContactCustomer contactCustomer) {
		this.contactCustomer = contactCustomer;
	}

	public Set<Loan> getLoans() {
		return this.loans;
	}

	public void setLoans(Set<Loan> loans) {
		this.loans = loans;
	}

	public String getMail() {
		return mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

}
