package acme.server.entity;

// Generated 30/11/2011 12:52:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * KindMaterial generated by hbm2java
 */
public class KindMaterial implements java.io.Serializable {

	private long idKindMaterial;
	private String name;
	private String letters;
	private Set<Material> materials = new HashSet<Material>(0);

	public KindMaterial() {
	}

	public KindMaterial(long idKindMaterial) {
		this.idKindMaterial = idKindMaterial;
	}

	public KindMaterial(long idKindMaterial, String name, String letters,
			Set<Material> materials) {
		this.idKindMaterial = idKindMaterial;
		this.name = name;
		this.letters = letters;
		this.materials = materials;
	}

	public long getIdKindMaterial() {
		return this.idKindMaterial;
	}

	public void setIdKindMaterial(long idKindMaterial) {
		this.idKindMaterial = idKindMaterial;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLetters() {
		return this.letters;
	}

	public void setLetters(String letters) {
		this.letters = letters;
	}

	public Set<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set<Material> materials) {
		this.materials = materials;
	}

}
