package acme.server.entity;

// Generated 30/11/2011 12:52:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material implements java.io.Serializable {

	private Long idMaterial;
	private Collection collection;
	private KindMaterial kindMaterial;
	private Classification classification;
	private String name;
	private Long units;
	private String edition;
	private Date publishDate;
	private Boolean available;
	private String code;
	private Set<Author> authors = new HashSet<Author>(0);
	private Set<Loan> loans = new HashSet<Loan>(0);

	public Material() {
	}

	public Material(Collection collection, KindMaterial kindMaterial,
			Classification classification, String name, Long units,
			String edition, Date publishDate, Boolean available, String code,
			Set<Author> authors, Set<Loan> loans) {
		this.collection = collection;
		this.kindMaterial = kindMaterial;
		this.classification = classification;
		this.name = name;
		this.units = units;
		this.edition = edition;
		this.publishDate = publishDate;
		this.available = available;
		this.code = code;
		this.authors = authors;
		this.loans = loans;
	}

	public Long getIdMaterial() {
		return this.idMaterial;
	}

	public void setIdMaterial(Long idMaterial) {
		this.idMaterial = idMaterial;
	}

	public Collection getCollection() {
		return this.collection;
	}

	public void setCollection(Collection collection) {
		this.collection = collection;
	}

	public KindMaterial getKindMaterial() {
		return this.kindMaterial;
	}

	public void setKindMaterial(KindMaterial kindMaterial) {
		this.kindMaterial = kindMaterial;
	}

	public Classification getClassification() {
		return this.classification;
	}

	public void setClassification(Classification classification) {
		this.classification = classification;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getUnits() {
		return this.units;
	}

	public void setUnits(Long units) {
		this.units = units;
	}

	public String getEdition() {
		return this.edition;
	}

	public void setEdition(String edition) {
		this.edition = edition;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public Boolean getAvailable() {
		return this.available;
	}

	public void setAvailable(Boolean available) {
		this.available = available;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set<Author> getAuthors() {
		return this.authors;
	}

	public void setAuthors(Set<Author> authors) {
		this.authors = authors;
	}

	public Set<Loan> getLoans() {
		return this.loans;
	}

	public void setLoans(Set<Loan> loans) {
		this.loans = loans;
	}

}
