package acme.server.entity;

// Generated 30/11/2011 12:52:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TicketPrice generated by hbm2java
 */
public class TicketPrice implements java.io.Serializable {

	private long idTicket;
	private String name;
	private Double value;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);
	private Set<Collection> collections = new HashSet<Collection>(0);

	public TicketPrice() {
	}

	public TicketPrice(long idTicket) {
		this.idTicket = idTicket;
	}

	public TicketPrice(long idTicket, String name, Double value,
			Set<Ticket> tickets, Set<Collection> collections) {
		this.idTicket = idTicket;
		this.name = name;
		this.value = value;
		this.tickets = tickets;
		this.collections = collections;
	}

	public long getIdTicket() {
		return this.idTicket;
	}

	public void setIdTicket(long idTicket) {
		this.idTicket = idTicket;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

	public Set<Collection> getCollections() {
		return this.collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

}
