package acme.server.entity;

// Generated 30/11/2011 12:52:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

	private long idLoan;
	private TicketPrice ticketPrice;
	private Loan loan;
	private String comments;
	private Long days;
	private Boolean isPaid;

	public Ticket() {
	}

	public Ticket(Loan loan) {
		this.loan = loan;
	}

	public Ticket(TicketPrice ticketPrice, Loan loan, String comments,
			Long days, Boolean isPaid) {
		this.ticketPrice = ticketPrice;
		this.loan = loan;
		this.comments = comments;
		this.days = days;
		this.isPaid = isPaid;
	}

	public long getIdLoan() {
		return this.idLoan;
	}

	public void setIdLoan(long idLoan) {
		this.idLoan = idLoan;
	}

	public TicketPrice getTicketPrice() {
		return this.ticketPrice;
	}

	public void setTicketPrice(TicketPrice ticketPrice) {
		this.ticketPrice = ticketPrice;
	}

	public Loan getLoan() {
		return this.loan;
	}

	public void setLoan(Loan loan) {
		this.loan = loan;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Long getDays() {
		return this.days;
	}

	public void setDays(Long days) {
		this.days = days;
	}

	public Boolean getIsPaid() {
		return this.isPaid;
	}

	public void setIsPaid(Boolean isPaid) {
		this.isPaid = isPaid;
	}

}
